baseurl = "http://hugo.spf13.com/"
disqusShortname = "shortname"
googleAnalytics = ""
languageCode = "en-us"
paginate = 3
preserveTaxonomyNames = true
publishDir = "docs"
theme = "hugo-future-imperfect"
title = "Talk Some Cents"
[[menu.main]]
name = "About"
url = "/about"
weight = 3
[[menu.main]]
name = "Categories"
url = "/categories"
weight = 2
[[menu.main]]
identifier = "fa fa-newspaper-o"
name = "Blog"
url = "/blog"
weight = 1
[params]
categoriesbycount = true
customcss = ["/css/main.min.css"]
customjs = ["/js/main.min.js"]
description = "HTML5 UP theme, Future Imperfect with some extra goodies, ported by Julio Pescador. Powered by Hugo"
faviconversion = ""
includereadingtime = true
loadfavicon = false
navbartitle = "Talk Some Cents"
socialappearatbottom = true
socialappearattop = true
viewmorepostlink = "/blog/"
[params.intro]
about = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent tellus lacus, auctor vehicula molestie quis, tempor quis velit. Quisque in quam ac leo efficitur vulputate. Phasellus ullamcorper aliquam sodales. Maecenas sit amet condimentum ipsum. Proin sit amet ligula elit. Mauris."
paragraph = "Another fine responsive site template by <a href=\"http://html5up.net\">HTML5 UP</a>. Ported by Julio Pescador with some extra goodies <i class='fa fa-hand-peace-o'></i>"
[params.intro.pic]
alt = "Talk Some Cents"
circle = false
imperfect = true
src = "/img/main/logo.png"
width = ""
[params.postamount]
sidebar = 2
[social]
behance = ""
bitbucket = ""
codepen = ""
deviantart = ""
dribbble = ""
email = ""
facebook = ""
facebook_admin = ""
flickr = ""
foursquare = ""
github = "jpescador"
googleplus = ""
instagram = ""
jsfiddle = ""
linkedin = ""
medium = ""
pinterest = ""
reddit = ""
slideshare = ""
stackoverflow = ""
tumblr = ""
twitter = "julio_pescador"
twitter_domain = ""
vimeo = ""
vine = ""
wordpress = ""
xing = ""
youtube = ""
